import { PAIRS } from "@uniswap-v2-pair-metrics/shared";
import type { Pool } from "pg";
import { loadConfig } from "./config.ts";
import { createPool } from "./db/index.ts";

/** By symbol rather than by index: a reordered PAIRS must not silently retarget a test. */
function addressOf(symbols: string): string {
  const pair = PAIRS.find((p) => `${p.token0Symbol}/${p.token1Symbol}` === symbols);

  if (pair === undefined) {
    throw new Error(`${symbols} is not in PAIRS`);
  }

  return pair.address;
}

export const ACTIVE = addressOf("USDC/WETH");
export const DEAD = addressOf("WETH/RKFL");

/** 2026-08-12 09:00:00 UTC, hour-aligned. */
export const HOUR = 1_786_525_200;

export function testPool(): Pool {
  return createPool(loadConfig().databaseUrl);
}

/**
 * The driver's own failure is `Failed query: delete from "pair_hour_metrics"`, which says
 * nothing about the database being down or how to start it.
 */
export async function assertReachable(pool: Pool): Promise<void> {
  try {
    const client = await pool.connect();
    client.release();
  } catch (cause) {
    throw new Error(
      "cannot reach the database these tests need. Start it and apply the schema:\n" +
        "  docker compose up -d db\n" +
        "  pnpm db:migrate",
      { cause },
    );
  }
}

/** A stored hour. `feesUsd` is generated by the column, so it is never supplied. */
export function storedRow(pairAddress: string, hourStartUnix: number) {
  return {
    pairAddress,
    hourStartUnix,
    reserve0: "17000000",
    reserve1: "5000",
    reserveUsd: "17689022.77",
    volumeToken0: "1000",
    volumeToken1: "0.3",
    volumeUsd: "1000",
    hourlyTxns: 12,
  };
}
