/** A stored hour. `feesUsd` is generated by the column, so it is never supplied. */
export function storedRow(pairAddress: string, hourStartUnix: number) {
  return {
    pairAddress,
    hourStartUnix,
    reserve0: "17000000",
    reserve1: "5000",
    reserveUsd: "17689022.77",
    volumeToken0: "1000",
    volumeToken1: "0.3",
    volumeUsd: "1000",
    hourlyTxns: 12,
  };
}
